name: README Generator

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cachce node_modules
        uses: actions/cache@v2
        id: node-cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install node_modules
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Generate README file
        run: node README-generator.js

      - name: Listup
        run: ls
